# Generated by Django 6.0.1 on 2026-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default='Novice Citizen', max_length=50),
        ),
    ]
