# Generated by Django 6.0.1 on 2026-01-12 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
