# Generated by Django 6.0.1 on 2026-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
