# Generated by Django 6.0.1 on 2026-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_sla_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if verified as a genuine issue'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='workflow_state',
            field=models.CharField(default='pending_verification', help_text='Current stage in approval workflow', max_length=50),
        ),
    ]
