# Generated by Django 6.0.1 on 2026-01-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_is_verified_complaint_workflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='workflow_state',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified_by_officer', 'Verified by Officer'), ('forwarded_to_redressal', 'Forwarded to Redressal'), ('resolved', 'Resolved')], default='pending_verification', help_text='Current stage in approval workflow', max_length=50),
        ),
    ]
