# Generated by Django 6.0.1 on 2026-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_workflow_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection by officer', null=True),
        ),
    ]
