# Generated by Django 6.0.1 on 2026-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_final_verified',
            field=models.BooleanField(default=False, help_text='True if local officer verifies the resolution'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
