# Generated by Django 6.0.1 on 2026-01-15 05:01

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_is_final_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=complaints.models.Complaint.complaint_directory_path),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_photo',
            field=models.ImageField(blank=True, null=True, upload_to=complaints.models.Complaint.resolution_directory_path),
        ),
    ]
